
export const AppConfig = {
    MOVIEBUNKERS_API: process.env.NEXT_PUBLIC_MOVIEBUNKERS_API,
    MOVIEBUNKERS_IMAGES: process.env.NEXT_PUBLIC_MOVIEBUNKERS_IMAGES,
    MOVIEBUNKERS_GUEST_TOKEN: process.env.NEXT_PUBLIC_MOVIEBUNKERS_GUEST_TOKEN,
    TMDB_API: process.env.NEXT_PUBLIC_TMDB_API_WRAPPER,
    GUEST_USERNAME: process.env.NEXT_PUBLIC_GUEST_USERNAME,
    GUEST_PASSWORD: process.env.NEXT_PUBLIC_GUEST_PASSWORD,
}