
export const AppConfig = {
    MOVIEBUNKERS_API: process.env.NEXT_PUBLIC_MOVIEBUNKERS_API,
    MOVIEBUNKERS_IMAGES: process.env.NEXT_PUBLIC_MOVIEBUNKERS_IMAGES,
    TMDB_API: process.env.NEXT_PUBLIC_TMDB_API_WRAPPER,
}